### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Fi5t** [kelposun/AirQualityMonitor#45]
Please, add `gradle-scripts/signing.gradle` to your project. I don't want to implement it from scratch. Thank you.

**Comment by kelposun** [comment]
Hi! You need to generate 2 key files (in Android Studio Build->Generate Signed Bundle [choose APK] -> Next -> [below "Key store path"] Create new) for release and debug, and obtain API key from [AirVisual API](https://www.airvisual.com/dashboard/api). Next you can create file signing.gradle with content showed below. Be careful API_KEY parameter must content quotes inside quotes :)

`ext {
    RELEASE_STORE_FILE = '<value>'
    RELEASE_STORE_PASSWORD = '<value>'
    RELEASE_KEY_ALIAS = '<value>'
    RELEASE_KEY_PASSWORD = '<value>'

    DEBUG_STORE_FILE = '<value>'
    DEBUG_STORE_PASSWORD = '<value>'
    DEBUG_KEY_ALIAS = '<value>'
    DEBUG_KEY_PASSWORD = '<value>'

    API_KEY = '"<value>"'
}`

**Comment by kelposun** [comment]
Another way: You can remove signing options in app level build.gradle file, but you steel need an API_KEY
